apiVersion: v1
kind: Service
metadata:
 name: admin
 labels:
   run: admin
spec:
 type: NodePort
 ports:
   - port: 3000
     targetPort: 3000
     nodePort: 30002
     protocol: TCP
 selector:
   run: admin
