apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  labels:
    run: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      run: admin
  template:
    metadata:
      labels:
        run: admin
    spec:
      containers:
      - name: admin
        image: registry.ng.bluemix.net/la_factory/admin-image
        ports:
        - containerPort: 3000
