apiVersion: v1
kind: Service
metadata:
 name: auth
 labels:
   run: auth
spec:
 type: NodePort
 ports:
   - port: 7000
     targetPort: 7000
     nodePort: 30001
     protocol: TCP
 selector:
   run: auth
