apiVersion: v1
kind: Service
metadata:
 name: chat
 labels:
   run: chat
spec:
 type: NodePort
 ports:
   - port: 5000
     targetPort: 5000
     nodePort: 30005
     protocol: TCP
 selector:
   run: chat
