apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    run: server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: server
  template:
    metadata:
      labels:
        run: server
    spec:
      containers:
      - name: server
        image: registry.ng.bluemix.net/la_factory/server-image
        ports:
        - containerPort: 8080
