apiVersion: v1
kind: Service
metadata:
 name: server
 labels:
   run: server
spec:
 type: NodePort
 ports:
   - port: 8080
     targetPort: 8080
     nodePort: 30100
     protocol: TCP
 selector:
   run: server
